config/routes.rb
Nusbrew::Application.routes.draw do
  devise_for :brewers, :controllers => {:registrations =>"registrations"}

  root 'places#index'

    resources :brewers
    resources :stocks
    get 'mystocks' => 'stocks#own'
    get 'invite'=> 'brewers#invite'
    resources :brews
    resources :places

end

app/models/brew.rb
class Brew < ActiveRecord::Base
	validates_presence_of :name, :liquor_type, :liters
end

app/models/brewer.rb
class Brewer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :inviter
  validates :name,
  	:uniqueness =>{
  		:message=> "Try a different name."
  	}
  def invite_address
  	"nusbrew.herokuapp.com/brewers/sign_up?inviter=" + name
  end

  def email_required?
  	false
  end
  def email_changed?
  	false
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :name,
	  	:uniqueness =>{
	  		:case_sensitive => false
	  	}
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :brew
  belongs_to :brewer
  belongs_to :place

  validates_presence_of :place, :brewer, :brew
  validates_numericality_of :quantity, only_integer: true, message: "had better be a whole number."
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, 
                                                             :inviter_name, :remember_me,
                                                             :home_base_id) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/brewers_controller.rb
class BrewersController < ApplicationController
	def create
		@brewer = Brewer.new(params[:brewer].permit(:name, :password, :confirm_password))
		if(@brewer.password == params[:brewer][:confirm_password])
			if @brewer.save
				flash[:notice] = "Yay! welcome on board!"
				redirect_to @brewer
			end
		else
			flash[:danger] = "Type password twice, how hard is that?"
			render 'new'
		end
	end

	def show
		@brewer = Brewer.find(params[:id])
		@invited = Brewer.where(inviter_name:@brewer.name)
		@stocks = Stock.where(brewer:@brewer)
		#logger.error current_brewer.invite_address
	end

	def invite
	end
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController
end

app/controllers/invite_controller.rb
class InviteController < ApplicationController
	def error
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@liquor_type = Brew.uniq.pluck('liquor_type')
		@liquor_type.sort!
		@places = Place.all(order:'name')
		@placesNames = Place.uniq.pluck('name')
		@bar = LazyHighCharts::HighChart.new('column') do |f|
			@liquor_type.each do |l|
				data = []
				#logger.error l.inspect
				@places.each do |p|
					@typesInP = Stock.where(place:p).where(liquor_type:l)
					sum = 0
					@typesInP.each do |t|
						sum += t.brew.liters * t.quantity
					end
					data.push(sum)
				end
				f.series(:name=>l,:data=> data)
			end    
	      f.title({ :text=>"Stash across NUS"})
	      f.xAxis({categories:@placesNames.sort!})
	      f.yAxis({title:{text:"Liters"}})
	      f.legend({:align => 'right', 
                    :x => -100, 
                    :verticalAlign=>'top',
                    :y=>100,
                    :backgroundColor=>'#FFFFFF',
                    :borderColor=>'#CCC',
                    :borderWidth=>1,
                    :shadow=>"false"
                    })
	      f.options[:legend][:layout]='vertical'
	      ###  Options for Bar
	      ### f.options[:chart][:defaultSeriesType] = "bar"
	      ### f.plot_options({:series=>{:stacking=>"normal"}}) 

	      ## or options for column
	      f.options[:chart][:defaultSeriesType] = "column"
	      f.plot_options({:column=>{:stacking=>"normal"}})
	    end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		@mybrewer = Brewer.new
		@mybrewer.inviter_name = params[:inviter]
		super
	end
	def create
		nameCheck = Brewer.find_by_name(params[:brewer][:name])
		@mybrewer = Brewer.new(params[:brewer].permit(:name, :password, 
									:password_confirmation, :inviter_name, :home_base_id))
		unless nameCheck.nil?
			flash[:warning] = "\""+nameCheck.name+"\""+ " already taken. Pick another name."
			render 'new' and return
		end
		@inviter = Brewer.find_by_name(params[:brewer][:inviter_name])
		if @inviter.nil?
			flash[:warning] = "Invalid inviter"
			render 'new' and return
			#redirect_to bad_invite_path
		end
		if params[:brewer][:home_base_id].nil? ||
				params[:brewer][:home_base_id]==""
			flash[:warning] = "Pick a home base!"
			render 'new' and return
		end
	    super
	    @inviter.invited_count += 1
		@inviter.save!
		logger.info "newBrewer: " + @mybrewer.inspect
	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	def new
		@stock = Stock.new
		unless brewer_signed_in?
			render new_brewer_session_path and return
		end
		@stock.place = Place.find(current_brewer.home_base_id)
	end
	def create
		@stock = Stock.new
		unless brewer_signed_in?
			render new_brewer_session_path and return
		else
			@stock.brewer = current_brewer
		end

		if params[:stock][:brew_id]==""
			flash[:warning] = "Please choose a brew"
		else
			brew = Brew.find(params[:stock][:brew_id])
		end

		if params[:stock][:place_id]==""
			flash[:warning] = "Please choose a place"
		else
			place = Place.find(params[:stock][:place_id])
		end
		@stock = Stock.find_or_initialize_by(brewer:current_brewer,
											brew:brew,
											liquor_type:brew.liquor_type,
											place:place)
		quantity = Integer(params[:stock][:quantity]) rescue 0
		@stock.quantity += quantity

		if @stock.save
			flash[:success] = 'Stocks updated!'
			logger.info "newStock: " + @stock.inspect
			redirect_to mystocks_path
		else
			flash[:warning] = @stock.errors.full_messages.to_sentence
			render 'new'
		end
	end
	def index
		@stocks = Stock.all
	end
	def own
		@stocks = Stock.where(:brewer=>current_brewer)
	end
	def show
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brewers_helper.rb
module BrewersHelper
end

app/helpers/brews_helper.rb
module BrewsHelper
end

app/helpers/invite_helper.rb
module InviteHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/brewers/invite.html.erb
<h2>How to invite</h2>
<p>Send this link to your drinking buddies in NUS!</p>
<p><code><%= current_brewer.invite_address%></code></p>

app/views/brewers/new.html.erb
<h2>Sign up</h2>
<%= render 'layouts/flash_message' %>
<%= form_for :brewer, class:"form-inline", :url => brewers_path do |f| %>
    <div class="form-group row">
		<div class="col-lg-offset-2 col-lg-3">
		<%= f.text_field :name, class:" form-control", :placeholder=>"user id" %>
		</div>
	</div>
	<div class="form-group row">
		<div class="col-lg-offset-2 col-lg-3">
		<%= f.password_field :password, class:" form-control", :placeholder=>"password" %>
		</div>
	</div>
	<div class="form-group row">
		<div class="col-lg-offset-2 col-lg-3">
		<%= f.password_field :confirm_password, class:" form-control", :placeholder=>"confirm password" %>
		</div>
	</div>
	 <div class="row"><%= f.submit "Sign up", class:"btn btn-large btn-success col-lg-2 col-lg-offset-2"%></div>
	<%end%>

app/views/brewers/show.html.erb
<%= render 'layouts/flash_message' %>
<h2>Drinker profile for: <strong><%=@brewer.name%></strong></h2>
<table>
	<tr>
		<td>Invited by: </td>
		<td><strong><%=@brewer.inviter_name%></strong></td>
	<tr>
	<tr>
		<td>Has invited:</td>
	</tr>
	<tr><td></td>
		<td><ul>
			<% @invited.each do |i|%>
				<li><%=link_to i.name, brewer_path(i.id)%><sup><%=i.invited_count%></sup></li>
			<%end%>
			</ul>
		</td>
	</tr>
	<tr><td><%=link_to "Invite more friends!", invite_path, class:"btn btn-default"%></td>
		<tr><td><br></td></tr>
	<tr>
		<td>Stash added:</td>
	</tr>
	<tr><td></td>
		<td>
			<ul>
			<% @stocks.each do |p| %>
				<li><%=p.quantity%> <%=p.brew.name%> at <%=p.place.name%></li>
			<% end %>
			</ul>
		</td>
	</tr>
</table>

app/views/layouts/_flash_message.html.erb
<div id="flash" class="text-center">
<% unless flash.empty? %>
	<% flash.each do |key, value| %>
		<%if key.to_s=="notice"%>
			<div class="alert alert-info">
	      		<%= value %>
	      	</div>
	    <% elsif key.to_s=="alert"%>
	      	<div class="alert alert-warning">
	      		<%= value %>
	      	</div>
	    <% else %>
		    <div class="alert alert-<%=key%>">
		        <%= value %>
		    </div>
		 <% end %>
	<% end %>
<% end %>
</div>

<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#flash').remove();
  }, 7000);
 })
</script>

app/views/layouts/_footer.html.erb
   
<nav class="navbar navbar-fixed-bottom navbar-default">
 <div class="containter">

  <% if brewer_signed_in? %>
     <div class="col-xs-4">
       <a>Send this to friends: <code><%= current_brewer.invite_address%></code></a>   
     </div><!--/ column-->
     <%end%>
     
     <div class="col-xs-4" style="text-align:center;">      
       
       <a>nusbrew &copy; 2014</a>
     
     </div><!--/ column-->
    <div class="col-xs-4">    
       <a>Updated 4-Feb-14</a>
     </div><!--/ column-->
   </div>
 </nav>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
            <strong><%= link_to "nusbrew", root_path, class:"navbar-brand", id:"brand"%></strong>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <% if brewer_signed_in? %>
              <li><p class="navbar-text" id="username">
                Hello <strong><%=current_brewer.name%>
                  <sup><%=current_brewer.invited_count%></sup>
                </strong>!
              </p></li>
              <li>
                <%= link_to "Add stock", new_stock_path, id:"add_stock"%>
              </li>
              <li><%= link_to "Profile", brewer_path(current_brewer.id) %></li>
              <li><%= link_to "Invite!", invite_path%></li>
              <li>  <%= link_to "Sign out", destroy_brewer_session_path, 
                                id: "sign_out", :method=>:delete %></li>
            <% else %>
              <li> <%= link_to "Sign in", new_brewer_session_path, id: "sign_in" %></li>
              <li> <%= link_to "Sign up", new_brewer_registration_url %></li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nusbrew</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/flash_message' %>
<%= render 'layouts/navbar' %>
<div class="col-xs-offset-1">
<%= yield %>
</div>
<%= render 'layouts/footer'%>
</body>
</html>

app/views/places/index.html.erb
<div class="col-xs-10"><%= high_chart("my_bar_div", @bar) %></div>

app/views/stocks/index.html.erb
<h3>NUS stocks: </h3>
<% @stocks.each do |p| %>
	<p><%=p.quantity%> <%=p.brew.name%> at <%=p.place.name%>, by <%=p.brewer.name%></p>
<% end %>

app/views/stocks/new.html.erb
<div class="row">
	<h2 class="col-xs-offset-1 col-xs-9">Add a new stock </h2>
</div>
<%= form_for @stock, class:"form-inline row", :url => stocks_path do |f| %>
    <div class="form-group row">
    	<%= f.label :brew_id , class:"control-label col-xs-offset-1 col-xs-1"%>
		<div class="col-sm-4 col-xs-4">
		<%= f.collection_select(:brew_id, Brew.all(order:'name'), :id, :name, prompt:true)%>		</div>
	</div>
	<div class="form-group row">
		<%= f.label :place_id, class:"control-label col-xs-offset-1 col-xs-1"%>
		<div class="col-sm-4 col-xs-4">
		<%= f.collection_select(:place_id, Place.all, :id, :name, prompt:true)%>
		</div>
	</div>
	<div class="form-group row">

		<%= f.label :quantity, class:"control-label col-xs-offset-1 col-xs-1"%>
		<div class="col-sm-4 col-xs-4">
		<%= f.number_field :quantity, in:1...100, class:" form-control", :placeholder=>"how many?" %>
		</div>
	</div>

	 <div class="row"><%= f.submit "Save", class:"btn btn-large btn-success col-sm-4 col-xs-offset-1 col-xs-9"%></div>
<%end%>

app/views/stocks/own.html.erb
<h3>Your stocks: </h3>
<% @stocks.each do |p| %>
	<p><%=p.quantity%> <%=p.brew.name%> at <%=p.place.name%></p>
<% end %>
<%= link_to "See NUS's", root_path%>